import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./shared/Navbar";
import Footer from "./shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0b1120] text-white`}
      >
        {/* header */}
        <nav>
          <Navbar></Navbar>
        </nav>

        {/* main */}
        <main className="min-h-[88vh]">{children}</main>

        {/* footer */}
        <Footer></Footer>
      </body>
    </html>
  );
}
