import NextAuthProvider from "@/Providers/NextAuthProvider";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./shared/Footer";
import Navbar from "./shared/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-[#020617] dark:text-[#cbd5e1]`}
      >
        <NextAuthProvider>
          {/* header */}
          <nav>
            <Navbar></Navbar>
          </nav>

          {/* main */}
          <main className="min-h-[88vh]">{children}</main>

          {/* footer */}
          <Footer></Footer>
        </NextAuthProvider>
      </body>
    </html>
  );
}
